name: 'Save a cache (AWS S3)'
description: 'Save Cache artifacts in S3 like dependencies and build outputs to improve workflow execution time'
author: 'Github, Justvanilla'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save caches that can be restored on other platforms'
    default: 'false'
    required: false
  aws-bucket:
    description: 'An AWS S3 bucket to save cache'
    required: true
  aws-access-key-id:
    description: 'An AWS access key id to access the bucket'
    required: true
  aws-secret-access-key:
    description: 'An AWS secret access key to access the bucket'
    required: true
  aws-region:
    description: 'An AWS region where the bucket is located'
    required: true
runs:
  using: 'node20'
  main: '../dist/save-only/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
